name: Play JSON Update & Live Stream Deployment

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:

concurrency:
  group: play-json-deploy
  cancel-in-progress: false

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest

    env:
      STREAM_URL: ${{ secrets.RTMP_URL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Python Dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Pull Latest Changes
        run: git pull --rebase origin main

      - name: Run Movie Update Script (play.py)
        run: |
          if [ -f play.py ]; then python3 play.py; fi

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add play.json
          git commit -m "Updated play.json with new movies - $(date '+%Y-%m-%d %H:%M:%S')" --allow-empty
          git push

      - name: Install FFmpeg (Full Version)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg fonts-dejavu libavcodec-extra

      - name: Validate RTMP/SRT Secret
        run: |
          echo "Checking STREAM_URL..."
          if [ -z "${STREAM_URL}" ]; then
            echo "❌ ERROR: STREAM_URL is not set in secrets as RTMP_URL"
            exit 1
          else
            echo "✅ STREAM_URL is set."
          fi

      - name: Delay Before Streaming
        run: sleep 5

      - name: Start Live Stream (stream.py)
        run: |
          echo "Launching stream.py..."
          python3 stream.py
