name: Live Stream Deployment

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Ensures we can push changes if needed

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Create environment file
        run: |
          echo "RTMP_URL=${{ secrets.RTMP_URL }}" > .env

      - name: Run live stream script
        run: |
          export $(grep -v '^#' .env | xargs)  # Load environment variables
          nohup python3 stream.py > stream.log 2>&1 &
          echo "Stream started at $(date)" >> stream.log
          sleep 21500  # ~6 hours to match the schedule
