name: Play JSON Update & Live Stream Deployment

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install pyyaml

      - name: Run Script (play.py)
        run: python3 play.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add play.json
          git diff --staged --quiet || git commit -m "Updated play.json with new movies"
          git push

      - name: Pull Latest Changes
        run: git pull origin main

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Debug Secrets
        run: |
          echo "Checking if RTMP_URL is set..."
          if [ -z "${{ secrets.RTMP_URL }}" ]; then
            echo "❌ ERROR: RTMP_URL is NOT set!"
            exit 1
          else
            echo "✅ RTMP_URL is set."
          fi

      - name: Run live stream script (stream.py)
        env:
          RTMP_URL: ${{ secrets.RTMP_URL }}  # ✅ Pass RTMP_URL to stream.py
        run: python3 stream.py
