name: Video Stream

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    concurrency:
      group: video-stream
      cancel-in-progress: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install ffmpeg-python
          sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Run Stream Script
        run: python stream.py
