name: RTMP Stream

on:
  schedule:
    - cron: "0 */5 * * *"  # Runs every 5 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg python3 python3-pip

      - name: Install Python Modules
        run: pip3 install -r requirements.txt || echo "No dependencies to install"

      - name: Run Streaming Script
        run: python3 stream.py
